FROM python:3.9

ARG APP_VERSION="latest"
# ENV DONKEYKONG_VERSION ${APP_VERSION}
ENV PROJECT_NAME="donkeykong"

WORKDIR /code

COPY . .
ENV PIP_CONFIG_FILE pip.conf
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

RUN sed -i 's/\r$//' start.sh
RUN sed -i 's/\r$//' start-dev.sh
