# Generated by Django 4.0.5 on 2022-07-13 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcm', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deleted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
